---
- hosts: banter
  tasks:
  - name: Copy amd64 deb-pak
    copy:
      src: ~/workspace/experiment/deb-pak/ipop-vpn_19.7.10_amd64.deb
      dest: ~/workspace/experiment/docker/
  - name: Updating container image
    shell: ./setup.sh img
    args:
      chdir: ~/workspace/experiment
    become: no
