#!/bin/bash

cd /opt/ipop-vpn
pip3 --no-cache-dir install virtualenv
virtualenv --python=python3.6 ipop-venv
source ipop-venv/bin/activate
pip3 --no-cache-dir install psutil==5.6.3 sleekxmpp==1.3.3 requests==2.21.0 simplejson==3.16.0 ryu==4.30
cp /opt/ipop-vpn/controller/modules/switches-fixed.py /opt/ipop-vpn/ipop-venv/lib/python3.6/site-packages/ryu/topology/switches.py
deactivate
systemctl daemon-reload
systemctl enable ipop